server.servlet.context-path=/grabdeal

#MySQL configuration
#spring.datasource.url=jdbc:mysql://mysql.freehostia.com:3306/rajtal6_grabdeals
#spring.datasource.username=rajtal6_grabdeals
#spring.datasource.password=password
#spring.jpa.hibernate.ddl-auto=create
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


#spring.cloud.gcp.projectId=oceanic-will-299708
#spring.cloud.gcp.sql.instanceName=oceanic-will-299708:asia-south1:mysql-instance-m
#spring.cloud.gcp.sql.databaseName=grabdeals_db
#spring.cloud.gcp.sql.userName=grabdeals
#spring.cloud.gcp.sql.password=grabdeals

#spring.datasource.url=jdbc:mysql://google/deals?cloudSqlInstance=oceanic-will-299708:asia-south1:mysql-instance&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=root&password=grabdeal
#spring.datasource.username=root
#spring.datasource.password=grabdeal
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.properties.hibernate.format_sql=true


spring.cloud.gcp.sql.database-name=grabdeals_db
spring.cloud.gcp.sql.instance-connection-name=grabdeals-12345:asia-south1:grabdeals-mysql

# So app starts despite "table already exists" errors.
spring.datasource.continue-on-error=true
# Enforces database initialization
spring.datasource.initialization-mode=always

# Leave empty for root, uncomment and fill out if you specified a user
spring.datasource.username=grabdeals

# Uncomment if root password is specified
spring.datasource.password=grabdeals

spring.cloud.gcp.project-id=grabdeals-12345

app.deploy.projectId=grabdeals-12345
#spring.cloud.gcp.credentials.location=file:/path/to/service-account.json




#custom properties
app.otp_length=6
